version: '3.8'
services:
  apirone-invoice-php:
    build:
      context: ./config-docker
      args:
        VERSION: 7.4
    volumes:
      - ./src:/var/www/html/
      - ./vendor:/var/www/vendor/
      - ./config-docker/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=9003"
      XDEBUG_MODE: develop,debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
  # Maria DB container
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    ports:
      - '3306:3306'
