version: '3.8'
services:
  apache:
    build:
      context: ./
      dockerfile: ./dev-docker/Dockerfile
      args:
        VERSION: 7.4
    volumes:
      - ./examples:/var/www/html/
      - ./src:/var/www/src/
      - ./src/assets:/var/www/html/assets
      - ./vendor:/var/www/vendor
      - ./dev-docker/settings:/var/www/settings/
      - ./dev-docker/php.ini:/usr/local/etc/php/php.ini
      - ./composer.json:/var/www/composer.json
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=9003"
      XDEBUG_MODE: develop,debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
  # Maria DB container
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./dev-docker/data/mysql:/var/lib/mysql
      - ./dev-docker/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - '3306:3306'
